using Clew.DAL;

namespace Clew.DAL
{
    public static class SeedDataProvider
    {
        public static List<Category> GetCategories()
        {
            return new List<Category>
            {
                new Category { Id = "ct1", Name = "Rings",     Image = "/images/category/RingCat.png"     },
                new Category { Id = "ct2", Name = "Earrings",  Image = "/images/category/EaringCat.png"   },
                new Category { Id = "ct3", Name = "Necklaces", Image = "/images/category/NecklaceCat.png" },
                new Category { Id = "ct4", Name = "Bracelets", Image = "/images/category/BraceletCat.png" },
                new Category { Id = "ct5", Name = "Watches",   Image = "/images/category/WatchCat.png"    }
            };
        }

        public static List<Product> GetProducts()
        {
            return new List<Product>
            {
                new Product { Id="p1",  CategoryId="ct1", Name="Classic Solitaire Diamond Ring",      Price=100,   Material="diamond", ProductCode="RG-001", Stock=10, Status="In Stock",    Description="Elegant solitaire ring featuring a brilliant-cut diamond in a timeless prong setting."                        },
                new Product { Id="p2",  CategoryId="ct1", Name="Vintage Floral Gold Ring",            Price=75,    Material="gold",    ProductCode="RG-002", Stock=5,  Status="In Stock",    Description="Antique-inspired gold ring with intricate floral engravings and ornate detailing."                            },
                new Product { Id="p3",  CategoryId="ct1", Name="Modern Halo Engagement Ring",         Price=1999,  Material="diamond", ProductCode="RG-003", Stock=2,  Status="In Stock",    Description="Contemporary engagement ring with a center stone surrounded by a dazzling halo of diamonds."                 },
                new Product { Id="p4",  CategoryId="ct1", Name="Three Stone Anniversary Ring",        Price=1750,  Material="silver",  ProductCode="RG-004", Stock=3,  Status="In Stock",    Description="Symbolic three-stone ring representing past, present, and future in white gold."                             },
                new Product { Id="p5",  CategoryId="ct1", Name="Cushion Cut Gemstone Ring",           Price=995,   Material="gold",    ProductCode="RG-005", Stock=7,  Status="In Stock",    Description="Stunning cushion-cut center stone in a delicate pavé band setting."                                         },
                new Product { Id="p6",  CategoryId="ct1", Name="Infinity Band Diamond Ring",          Price=1650,  Material="diamond", ProductCode="RG-006", Stock=4,  Status="In Stock",    Description="Romantic infinity design with continuous diamonds symbolizing eternal love."                                  },
                new Product { Id="p7",  CategoryId="ct1", Name="Art Deco Statement Ring",             Price=1850,  Material="silver",  ProductCode="RG-007", Stock=6,  Status="In Stock",    Description="Bold Art Deco-inspired ring with geometric patterns and vintage gemstones."                                   },
                new Product { Id="p8",  CategoryId="ct1", Name="Princess Cut Wedding Ring",           Price=1950,  Material="diamond", ProductCode="RG-008", Stock=2,  Status="In Stock",    Description="Sophisticated princess-cut diamond in a classic four-prong platinum setting."                                },
                new Product { Id="p9",  CategoryId="ct1", Name="Rose Gold Twist Band Ring",           Price=875,   Material="gold",    ProductCode="RG-009", Stock=5,  Status="In Stock",    Description="Delicate rose gold band with an elegant twisted design and diamond accents."                                 },
                new Product { Id="p10", CategoryId="ct1", Name="Emerald Cut Cocktail Ring",           Price=1799,  Material="silver",  ProductCode="RG-010", Stock=3,  Status="In Stock",    Description="Glamorous emerald-cut statement ring perfect for special occasions."                                         },
                new Product { Id="p11", CategoryId="ct2", Name="Gold Drop Chandelier Earrings",       Price=695,   Material="gold",    ProductCode="ER-001", Stock=8,  Status="In Stock",    Description="Elegant chandelier-style drop earrings in lustrous yellow gold with intricate detailing."                    },
                new Product { Id="p12", CategoryId="ct2", Name="Diamond Stud Earrings",               Price=1450,  Material="diamond", ProductCode="ER-002", Stock=10, Status="In Stock",    Description="Classic diamond stud earrings in 14k gold with secure push-back closures."                                   },
                new Product { Id="p13", CategoryId="ct2", Name="Teardrop Pearl Earrings",             Price=525,   Material="silver",  ProductCode="ER-003", Stock=6,  Status="In Stock",    Description="Graceful teardrop-shaped pearl earrings with gold accents and gentle movement."                              },
                new Product { Id="p14", CategoryId="ct2", Name="Hoop Earrings with Gemstones",        Price=780,   Material="gold",    ProductCode="ER-004", Stock=4,  Status="In Stock",    Description="Medium-sized gold hoops adorned with colorful gemstones for everyday elegance."                              },
                new Product { Id="p15", CategoryId="ct2", Name="Vintage Filigree Dangle Earrings",    Price=925,   Material="silver",  ProductCode="ER-005", Stock=7,  Status="In Stock",    Description="Ornate vintage-style earrings featuring delicate filigree work and antique finish."                          },
                new Product { Id="p16", CategoryId="ct2", Name="Geometric Modern Earrings",           Price=450,   Material="gold",    ProductCode="ER-006", Stock=12, Status="In Stock",    Description="Contemporary geometric design in polished gold with clean, modern lines."                                    },
                new Product { Id="p17", CategoryId="ct2", Name="Halloween Crystal Drop Earrings",     Price=225,   Material="silver",  ProductCode="ER-007", Stock=15, Status="In Stock",    Description="Festive crystal earrings with unique seasonal design and sparkling accents."                                 },
                new Product { Id="p18", CategoryId="ct2", Name="Lever-Back Gold Earrings",            Price=1050,  Material="diamond", ProductCode="ER-008", Stock=3,  Status="In Stock",    Description="Secure lever-back earrings in 18k gold with cushion-cut center stones."                                     },
                new Product { Id="p19", CategoryId="ct2", Name="Circular Pavé Stud Earrings",         Price=1580,  Material="diamond", ProductCode="ER-009", Stock=5,  Status="In Stock",    Description="Round stud earrings completely covered in brilliant pavé-set diamonds."                                      },
                new Product { Id="p20", CategoryId="ct2", Name="Floral Cluster Earrings",             Price=675,   Material="gold",    ProductCode="ER-010", Stock=8,  Status="In Stock",    Description="Delicate floral cluster design in gold with multiple gemstone petals."                                       },
                new Product { Id="p21", CategoryId="ct3", Name="Layered Chain Necklace Set",          Price=245,   Material="gold",    ProductCode="NK-001", Stock=10, Status="In Stock",    Description="Multi-strand necklace set with varying chain lengths for a trendy layered look."                             },
                new Product { Id="p22", CategoryId="ct3", Name="Statement Gemstone Collar",           Price=1650,  Material="silver",  ProductCode="NK-002", Stock=0,  Status="Out of Stock",Description="Bold collar necklace featuring an array of colorful gemstones in ornate settings."                           },
                new Product { Id="p23", CategoryId="ct3", Name="Delicate Gold Chain Necklace",        Price=325,   Material="gold",    ProductCode="NK-003", Stock=2,  Status="Low Stock",   Description="Simple yet elegant thin gold chain perfect for everyday wear or layering."                                   },
                new Product { Id="p24", CategoryId="ct3", Name="Bridal Diamond Necklace Set",         Price=1999,  Material="diamond", ProductCode="NK-004", Stock=0,  Status="Inactive",    Description="Luxurious bridal necklace and earring set with cascading diamonds and intricate design."                    },
                new Product { Id="p25", CategoryId="ct3", Name="Solitaire Diamond Pendant",           Price=1495,  Material="diamond", ProductCode="NK-005", Stock=5,  Status="In Stock",    Description="Classic solitaire diamond pendant on a delicate chain, timeless and elegant."                               },
                new Product { Id="p26", CategoryId="ct3", Name="Art Deco Diamond Necklace",           Price=1850,  Material="diamond", ProductCode="NK-006", Stock=3,  Status="In Stock",    Description="Vintage-inspired Art Deco necklace with geometric diamond patterns and platinum setting."                   },
                new Product { Id="p27", CategoryId="ct3", Name="Riviera Diamond Tennis Necklace",     Price=1950,  Material="diamond", ProductCode="NK-007", Stock=4,  Status="In Stock",    Description="Stunning tennis necklace with continuous line of brilliant-cut diamonds."                                   },
                new Product { Id="p28", CategoryId="ct3", Name="Y-Drop Diamond Necklace",             Price=1750,  Material="silver",  ProductCode="NK-008", Stock=6,  Status="In Stock",    Description="Modern Y-shaped necklace with diamond-studded chain and elegant drop pendant."                              },
                new Product { Id="p29", CategoryId="ct3", Name="Halo Pendant Necklace",               Price=1280,  Material="gold",    ProductCode="NK-009", Stock=5,  Status="In Stock",    Description="Center diamond surrounded by halo of smaller stones on white gold chain."                                   },
                new Product { Id="p30", CategoryId="ct3", Name="Multi-Tier Diamond Statement Necklace",Price=1999, Material="diamond", ProductCode="NK-010", Stock=2,  Status="In Stock",    Description="Spectacular multi-layered diamond necklace perfect for formal occasions and galas."                          },
                new Product { Id="p31", CategoryId="ct4", Name="Gold Link Chain Bracelet",            Price=585,   Material="gold",    ProductCode="BR-001", Stock=7,  Status="In Stock",    Description="Classic gold link bracelet with secure clasp and timeless design."                                          },
                new Product { Id="p32", CategoryId="ct4", Name="Diamond Tennis Bracelet",             Price=1950,  Material="diamond", ProductCode="BR-002", Stock=4,  Status="In Stock",    Description="Elegant tennis bracelet featuring a continuous line of brilliant diamonds."                                  },
                new Product { Id="p33", CategoryId="ct4", Name="Beaded Gemstone Bracelet",            Price=225,   Material="silver",  ProductCode="BR-003", Stock=8,  Status="In Stock",    Description="Colorful beaded bracelet with semi-precious gemstones and stretch design."                                   },
                new Product { Id="p34", CategoryId="ct4", Name="Charm Bracelet Collection",           Price=595,   Material="gold",    ProductCode="BR-004", Stock=5,  Status="In Stock",    Description="Personalized charm bracelet with multiple dangling charms and gold chain."                                   },
                new Product { Id="p35", CategoryId="ct4", Name="Bangle Bracelet Set",                 Price=450,   Material="silver",  ProductCode="BR-005", Stock=3,  Status="In Stock",    Description="Set of three stackable gold bangles with textured and smooth finishes."                                      },
                new Product { Id="p36", CategoryId="ct4", Name="Cuff Bracelet with Gemstones",        Price=950,   Material="gold",    ProductCode="BR-006", Stock=2,  Status="In Stock",    Description="Wide cuff bracelet adorned with row of vibrant gemstones in gold setting."                                   },
                new Product { Id="p37", CategoryId="ct4", Name="Rope Chain Gold Bracelet",            Price=775,   Material="gold",    ProductCode="BR-007", Stock=6,  Status="In Stock",    Description="Twisted rope-style gold bracelet with substantial weight and elegant drape."                                 },
                new Product { Id="p38", CategoryId="ct4", Name="Pearl Strand Bracelet",               Price=525,   Material="silver",  ProductCode="BR-008", Stock=4,  Status="In Stock",    Description="Lustrous freshwater pearl bracelet with ornate gold clasp and spacers."                                      },
                new Product { Id="p39", CategoryId="ct4", Name="Cuban Link Gold Bracelet",            Price=1225,  Material="diamond", ProductCode="BR-009", Stock=2,  Status="In Stock",    Description="Bold Cuban link design in solid gold with secure box clasp."                                                },
                new Product { Id="p40", CategoryId="ct4", Name="Infinity Symbol Bracelet",            Price=385,   Material="silver",  ProductCode="BR-010", Stock=5,  Status="In Stock",    Description="Delicate bracelet featuring infinity symbol with diamond accents."                                           },
                new Product { Id="p41", CategoryId="ct5", Name="Classic Leather Strap Watch",         Price=850,   Material="silver",  ProductCode="WT-001", Stock=10, Status="In Stock",    Description="Timeless watch with brown leather strap, silver case, and minimalist dial."                                  },
                new Product { Id="p42", CategoryId="ct5", Name="Sport Chronograph Watch",             Price=1450,  Material="silver",  ProductCode="WT-002", Stock=5,  Status="In Stock",    Description="High-performance chronograph with tachymeter bezel and stainless steel band."                               },
                new Product { Id="p43", CategoryId="ct5", Name="Luxury Swiss Automatic Watch",        Price=1999,  Material="gold",    ProductCode="WT-003", Stock=3,  Status="In Stock",    Description="Premium Swiss-made automatic watch with exhibition caseback and sapphire crystal."                           },
                new Product { Id="p44", CategoryId="ct5", Name="Diver's Professional Watch",          Price=1650,  Material="silver",  ProductCode="WT-004", Stock=7,  Status="In Stock",    Description="Water-resistant dive watch with rotating bezel and luminous markers, rated to 300m."                        },
                new Product { Id="p45", CategoryId="ct5", Name="Women's Diamond Bezel Watch",         Price=1899,  Material="diamond", ProductCode="WT-005", Stock=2,  Status="In Stock",    Description="Elegant ladies' watch with diamond-set bezel and mother-of-pearl dial."                                     },
                new Product { Id="p46", CategoryId="ct5", Name="Smart Hybrid Watch",                  Price=950,   Material="silver",  ProductCode="WT-006", Stock=8,  Status="In Stock",    Description="Modern hybrid smartwatch combining traditional aesthetics with fitness tracking technology."                 },
                new Product { Id="p47", CategoryId="ct5", Name="Skeleton Mechanical Watch",           Price=1550,  Material="gold",    ProductCode="WT-007", Stock=4,  Status="In Stock",    Description="Open-worked skeleton watch showcasing intricate mechanical movement through transparent dial."               },
                new Product { Id="p48", CategoryId="ct5", Name="Rolex-Style Oyster Watch",            Price=1999,  Material="diamond", ProductCode="WT-008", Stock=2,  Status="In Stock",    Description="Luxury oyster-style watch with iconic design, jubilee bracelet, and ceramic bezel."                         },
                new Product { Id="p49", CategoryId="ct5", Name="Pilot's Aviation Watch",              Price=1750,  Material="silver",  ProductCode="WT-009", Stock=5,  Status="In Stock",    Description="Aviation-inspired timepiece with oversized crown and highly legible dial for pilots."                       },
                new Product { Id="p50", CategoryId="ct5", Name="Rose Gold Ladies' Dress Watch",       Price=1350,  Material="gold",    ProductCode="WT-010", Stock=6,  Status="In Stock",    Description="Sophisticated rose gold dress watch with slim profile and genuine leather strap."                           }
            };
        }
    }
}